openapi: 3.0.2
info:
  title: 'API '
  description: ''
  version: '1.0'
servers: []
paths:
  /resource:
    post:
      tags:
        - Resources
      summary: 'Create Post'
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        name:
                          type: string
                          example: John
                        age:
                          type: string
                          example: '10'
                    example:
                      -
                        id: 1
                        name: John
                        age: '10'
                  count:
                    type: integer
                    example: 1
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: John
                age:
                  type: string
                  example: John
